var mallMap = {
    "colors":{"fillColor":"#e4e4e4","lightColor":"#fff","darkColor":"#000"},
    "selectedColor":"All",
    "fontSize":8,
    "texture":"",
    "currentScale":1,
    "extraChartDivId":"",
    "extraChartData":[],
    "LOEData":[],
    "revenueData":[],
    "sunburstChart":"",
    "stackedBarChart":"",
    "wellData":{},
    "wellExtraData":{},
    "mainData":"",
    "extraData":"",
    "mapData":"",
    "myWellCount":25,
    "barDateRange":"all",
    "barDataFiltered":false,
    "selectedParentNode":"",
    "previousParentNode":"",
    "clickedNode":"",
    "wellNames": {},
    "currentExtraChart": "bar",
    "currentWellIds":[],
    "currentWellColours":{},
    "dateNodes":{},
    "barMenuGroups":[],
    "maxDepth":4,
    "tooltipExtraFields":{},
    "oppColors":{"actual":"#4682B4","downtime":"#A0A0A0","unidentified":"#FFA500"},
    "oppIds":{"actual":"-3-2-2-","downtime":"-3-2_1-","unidentified":"-3-2-3-"},
    "currentSelectedPath":"",
    "mapZoomLevel":1,
    "LOENodePath":"-3-3-",
    "currentExtraData":"REVENUE"
};
