var mallMap = {
    "colors":{"fillColor":"#e4e4e4","lightColor":"#fff","darkColor":"#000"},
    "selectedColor":"functional",
    "fontSize":8,
    "texture":"",
    "currentScale":1,
    "extraChartDivId":"",
    "extraChartData":{},
    "sunburstChart":"",
    "stackedBarChart":"",
    "wellData":{},
    "wellExtraData":{},
    "mainData":"",
    "extraData":"",
    "mapData":"",
    "myWellCount":25,
    "barDateRange":"all",
    "barDataFiltered":false,
    "selectedParentNode":"",
    "wellNames": {},
    "currentExtraChart": "bar",
    "currentWellIds":[],
    "currentWellColours":{},
    "dateNodes":{},
    "barMenuGroups":[],
    "maxDepth":4,
    "tooltipExtraFields":{},
    "oppColors":{"actual":"#4682B4","downtime":"#708090","unidentified":"#FFA500"},
    "oppIds":{"actual":"-3-2-2-","downtime":"-3-2_1-","unidentified":"-3-2-3-"},
    "currentSelectedPath":""
};
